#!/usr/bin/env python3
"""Preflight data-quality checks for regenerated Bybit leverage fixture.

Streams JSONL fixture and reports coverage/gaps/timestamp semantics needed before
Quant uses OI/funding/candle studies as evidence.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def parse_ts(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)


def bucket(ts: datetime, minutes: int) -> datetime:
    minute = (ts.minute // minutes) * minutes
    return ts.replace(minute=minute, second=0, microsecond=0)


def gap_stats(times: list[datetime], expected_minutes: int) -> dict[str, Any]:
    if len(times) < 2:
        return {
            "bucket_count": len(times),
            "max_gap_minutes": 0.0,
            "gaps_gt_expected": 0,
            "gaps_gt_1h": 0,
            "first": times[0].isoformat().replace("+00:00", "Z") if times else None,
            "last": times[-1].isoformat().replace("+00:00", "Z") if times else None,
        }
    gaps = [(b - a).total_seconds() / 60 for a, b in zip(times, times[1:])]
    return {
        "bucket_count": len(times),
        "max_gap_minutes": max(gaps),
        "gaps_gt_expected": sum(g > expected_minutes for g in gaps),
        "gaps_gt_1h": sum(g > 60 for g in gaps),
        "first": times[0].isoformat().replace("+00:00", "Z"),
        "last": times[-1].isoformat().replace("+00:00", "Z"),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("fixture", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    line_count = 0
    kind_counts: Counter[str] = Counter()
    symbol_counts: Counter[str] = Counter()
    kind_symbol_counts: Counter[str] = Counter()
    source_endpoints: Counter[str] = Counter()
    fixture_versions: Counter[str] = Counter()
    replay_visibility: Counter[str] = Counter()
    visibility_notes: Counter[str] = Counter()
    timestamp_issues: Counter[str] = Counter()
    raw_hash_missing = 0
    retrieved_at_missing = 0

    buckets_5m: dict[tuple[str, str, str], set[datetime]] = defaultdict(set)
    buckets_1h: dict[tuple[str, str, str], set[datetime]] = defaultdict(set)
    candle_keys: set[tuple[str, datetime]] = set()
    oi_keys: set[tuple[str, datetime]] = set()
    oi_raw_present: Counter[str] = Counter()
    oi_notional_present: Counter[str] = Counter()
    example_records: dict[str, dict[str, Any]] = {}

    with args.fixture.open("r", encoding="utf-8") as fh:
        for line in fh:
            line_count += 1
            row = json.loads(line)
            kind = row.get("kind", "UNKNOWN")
            symbol = row.get("symbol", "UNKNOWN")
            meta = row.get("metadata", {}) or {}
            payload = row.get("payload", {}) or {}
            market_type = meta.get("market_type", "unknown")
            key = f"{kind}|{symbol}|{market_type}"

            kind_counts[kind] += 1
            symbol_counts[symbol] += 1
            kind_symbol_counts[key] += 1
            source_endpoints[str(meta.get("source_endpoint"))] += 1
            fixture_versions[str(meta.get("fixture_version"))] += 1
            replay_visibility[str(meta.get("replay_visibility"))] += 1
            visibility_notes[str(meta.get("visibility_note"))] += 1
            if key not in example_records:
                example_records[key] = row
            if not meta.get("raw_payload_hash"):
                raw_hash_missing += 1
            if not meta.get("retrieved_at"):
                retrieved_at_missing += 1

            occurred_at_s = row.get("occurred_at")
            observed_at_s = row.get("observed_at")
            if not occurred_at_s:
                timestamp_issues["missing_occurred_at"] += 1
                continue
            if not observed_at_s:
                timestamp_issues["missing_observed_at"] += 1
                continue
            occurred_at = parse_ts(occurred_at_s)
            observed_at = parse_ts(observed_at_s)
            if observed_at < occurred_at:
                timestamp_issues["observed_before_occurred"] += 1

            b5 = bucket(occurred_at, 5)
            b1 = bucket(occurred_at, 60)
            buckets_5m[(kind, symbol, market_type)].add(b5)
            buckets_1h[(kind, symbol, market_type)].add(b1)

            if kind == "candle" and market_type == "linear_perp":
                candle_keys.add((symbol, b5))
            if kind == "perp_open_interest":
                oi_keys.add((symbol, b1))
                if payload.get("open_interest_raw") not in (None, ""):
                    oi_raw_present[symbol] += 1
                if payload.get("open_interest_notional_usdt") not in (None, ""):
                    oi_notional_present[symbol] += 1

    coverage_5m = {
        "|".join(k): gap_stats(sorted(v), 5) for k, v in sorted(buckets_5m.items())
    }
    coverage_1h = {
        "|".join(k): gap_stats(sorted(v), 60) for k, v in sorted(buckets_1h.items())
    }

    oi_candle_alignment: dict[str, Any] = {}
    for symbol in sorted({s for s, _ in oi_keys} | {s for s, _ in candle_keys}):
        oi_hours = {t for s, t in oi_keys if s == symbol}
        candle_hours = {bucket(t, 60) for s, t in candle_keys if s == symbol}
        oi_candle_alignment[symbol] = {
            "oi_hour_buckets": len(oi_hours),
            "linear_perp_candle_hour_buckets": len(candle_hours),
            "oi_hours_missing_any_linear_perp_candle": len(oi_hours - candle_hours),
            "linear_perp_candle_hours_missing_oi": len(candle_hours - oi_hours),
            "oi_raw_present_rows": oi_raw_present[symbol],
            "oi_notional_present_rows": oi_notional_present[symbol],
        }

    result = {
        "fixture": str(args.fixture),
        "line_count": line_count,
        "kind_counts": dict(kind_counts),
        "symbol_counts": dict(symbol_counts),
        "kind_symbol_market_counts": dict(kind_symbol_counts),
        "source_endpoints": dict(source_endpoints),
        "fixture_versions": dict(fixture_versions),
        "replay_visibility": dict(replay_visibility),
        "visibility_notes": dict(visibility_notes),
        "timestamp_issues": dict(timestamp_issues),
        "raw_payload_hash_missing_rows": raw_hash_missing,
        "retrieved_at_missing_rows": retrieved_at_missing,
        "coverage_5m": coverage_5m,
        "coverage_1h": coverage_1h,
        "oi_candle_alignment": oi_candle_alignment,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "fixture": str(args.fixture),
        "out": str(args.out),
        "line_count": line_count,
        "kind_counts": dict(kind_counts),
        "timestamp_issues": dict(timestamp_issues),
        "raw_payload_hash_missing_rows": raw_hash_missing,
        "retrieved_at_missing_rows": retrieved_at_missing,
        "oi_candle_alignment": oi_candle_alignment,
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
