#!/usr/bin/env python3
"""Leverage-State Classifier v2 first-pass event study.

Uses regenerated Bybit BTC/ETH fixture. Classifies hourly states from 24h price,
raw OI, and notional OI changes using rolling percentile gates, then compares
forward volatility/tail outcomes against matched controls.
"""

from __future__ import annotations

import argparse
import json
import math
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from statistics import mean
from typing import Any


def parse_ts(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc).replace(minute=0, second=0, microsecond=0)


def fl(value: Any) -> float | None:
    try:
        if value is None or value == "":
            return None
        return float(value)
    except Exception:
        return None


def pct(a: float | None, b: float | None) -> float | None:
    if a is None or b in (None, 0):
        return None
    return a / b - 1.0


def q(values: list[float], p: float) -> float | None:
    xs = sorted(v for v in values if v is not None and math.isfinite(v))
    if not xs:
        return None
    pos = (len(xs) - 1) * p
    lo = int(pos)
    hi = min(lo + 1, len(xs) - 1)
    f = pos - lo
    return xs[lo] * (1 - f) + xs[hi] * f


def std(values: list[float]) -> float | None:
    xs = [v for v in values if v is not None and math.isfinite(v)]
    if len(xs) < 2:
        return None
    m = mean(xs)
    return math.sqrt(sum((x - m) ** 2 for x in xs) / (len(xs) - 1))


def decile_edges(values: list[float]) -> list[float]:
    return [q(values, i / 10) for i in range(1, 10)]  # type: ignore[list-item]


def bin_idx(value: float | None, edges: list[float]) -> int | None:
    if value is None or not math.isfinite(value):
        return None
    i = 0
    while i < len(edges) and value > edges[i]:
        i += 1
    return i


def summarize(values: list[float | None]) -> dict[str, Any]:
    xs = [v for v in values if v is not None and math.isfinite(v)]
    if not xs:
        return {"n": 0, "mean": None, "median": None, "p10": None, "p90": None}
    return {"n": len(xs), "mean": mean(xs), "median": q(xs, 0.5), "p10": q(xs, 0.1), "p90": q(xs, 0.9)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("fixture", type=Path)
    parser.add_argument("--out-json", type=Path, required=True)
    parser.add_argument("--out-md", type=Path, required=True)
    parser.add_argument("--rolling-hours", type=int, default=2160)  # 90d
    args = parser.parse_args()

    # symbol -> hour -> fields
    H: dict[str, dict[datetime, dict[str, float]]] = defaultdict(lambda: defaultdict(dict))
    fixture_versions = set()
    replay_visibility = set()

    with args.fixture.open("r", encoding="utf-8") as fh:
        for line in fh:
            r = json.loads(line)
            sym = r["symbol"]
            kind = r["kind"]
            meta = r.get("metadata", {}) or {}
            payload = r.get("payload", {}) or {}
            fixture_versions.add(meta.get("fixture_version"))
            replay_visibility.add(meta.get("replay_visibility"))
            hr = parse_ts(r["occurred_at"])
            d = H[sym][hr]
            if kind == "candle" and meta.get("market_type") == "linear_perp":
                # Last 5m close encountered in each hour wins; fixture is chronological.
                close = fl(payload.get("close"))
                if close is not None:
                    d["close"] = close
            elif kind == "perp_open_interest":
                raw = fl(payload.get("open_interest_raw"))
                notional = fl(payload.get("open_interest_notional_usdt"))
                if raw is not None:
                    d["oi_raw"] = raw
                if notional is not None:
                    d["oi_notional"] = notional
            elif kind == "perp_funding_rate":
                rate = fl(payload.get("funding_rate")) or fl(payload.get("rate"))
                if rate is not None:
                    d["funding"] = rate

    states = ["true_deleverage", "passive_notional_shrink", "sticky_or_short_build", "risk_on_leverage_build"]
    horizons = [24, 48, 72]
    by_symbol: dict[str, Any] = {}

    for sym, rows_by_hour in sorted(H.items()):
        hours = sorted(rows_by_hour)
        close = [rows_by_hour[t].get("close") for t in hours]
        raw_oi = [rows_by_hour[t].get("oi_raw") for t in hours]
        notional_oi = [rows_by_hour[t].get("oi_notional") for t in hours]
        one_h_ret = [pct(close[i], close[i - 1]) if i >= 1 else None for i in range(len(hours))]
        ret_24 = [pct(close[i], close[i - 24]) if i >= 24 else None for i in range(len(hours))]
        raw_oi_24 = [pct(raw_oi[i], raw_oi[i - 24]) if i >= 24 else None for i in range(len(hours))]
        notional_oi_24 = [pct(notional_oi[i], notional_oi[i - 24]) if i >= 24 else None for i in range(len(hours))]
        rv_24 = []
        for i in range(len(hours)):
            vals = [v for v in one_h_ret[max(1, i - 23) : i + 1] if v is not None]
            rv_24.append(math.sqrt(sum(v * v for v in vals)) if len(vals) >= 20 else None)

        fwd: dict[int, dict[str, list[float | None]]] = {}
        for h in horizons:
            fwd_ret = []
            fwd_abs = []
            fwd_rv = []
            fwd_mae = []
            for i in range(len(hours)):
                if i + h >= len(hours) or close[i] in (None, 0):
                    fwd_ret.append(None); fwd_abs.append(None); fwd_rv.append(None); fwd_mae.append(None); continue
                c0_maybe = close[i]
                if c0_maybe is None or c0_maybe == 0:
                    fwd_ret.append(None); fwd_abs.append(None); fwd_rv.append(None); fwd_mae.append(None); continue
                c0: float = c0_maybe
                c1 = close[i + h]
                rets = [r for r in (one_h_ret[j] for j in range(i + 1, i + h + 1)) if r is not None]
                path = [r for r in (pct(close[j], c0) for j in range(i + 1, i + h + 1) if close[j] is not None) if r is not None]
                fr = pct(c1, c0)
                fwd_ret.append(fr)
                fwd_abs.append(abs(fr) if fr is not None else None)
                fwd_rv.append(math.sqrt(sum(r * r for r in rets)) if len(rets) >= max(4, h // 2) else None)
                fwd_mae.append(min(path) if path else None)
            fwd[h] = {"return": fwd_ret, "abs_return": fwd_abs, "rv": fwd_rv, "mae": fwd_mae}

        eligible = []
        classified: dict[str, list[int]] = {s: [] for s in states}
        for i in range(args.rolling_hours + 24, len(hours) - max(horizons)):
            needed = [ret_24[i], raw_oi_24[i], notional_oi_24[i], rv_24[i]]
            if any(v is None or not math.isfinite(v) for v in needed):
                continue
            window_raw = [v for v in raw_oi_24[i - args.rolling_hours : i] if v is not None and math.isfinite(v)]
            window_notional = [v for v in notional_oi_24[i - args.rolling_hours : i] if v is not None and math.isfinite(v)]
            window_ret = [v for v in ret_24[i - args.rolling_hours : i] if v is not None and math.isfinite(v)]
            if len(window_raw) < args.rolling_hours * 0.8 or len(window_notional) < args.rolling_hours * 0.8:
                continue
            raw_q20, raw_q50, raw_q80 = q(window_raw, 0.2), q(window_raw, 0.5), q(window_raw, 0.8)
            not_q20, not_q50, not_q80 = q(window_notional, 0.2), q(window_notional, 0.5), q(window_notional, 0.8)
            ret_q25, ret_q75 = q(window_ret, 0.25), q(window_ret, 0.75)
            if None in [raw_q20, raw_q50, raw_q80, not_q20, not_q50, not_q80, ret_q25, ret_q75]:
                continue
            assert raw_q20 is not None and raw_q50 is not None and raw_q80 is not None
            assert not_q20 is not None and not_q50 is not None and not_q80 is not None
            assert ret_q25 is not None and ret_q75 is not None
            eligible.append(i)
            r24 = ret_24[i]
            raw24 = raw_oi_24[i]
            not24 = notional_oi_24[i]
            if r24 is None or raw24 is None or not24 is None:
                continue
            # Quantiles have been checked for None above; assign concrete float names for clarity.
            raw20 = float(raw_q20); raw50 = float(raw_q50); raw80 = float(raw_q80)
            not20 = float(not_q20); not80 = float(not_q80)
            ret25 = float(ret_q25); ret75 = float(ret_q75)
            price_down = r24 <= ret25
            price_up = r24 >= ret75
            if price_down and not24 <= not20 and raw24 <= raw20:
                classified["true_deleverage"].append(i)
            if price_down and not24 <= not20 and raw24 >= raw50:
                classified["passive_notional_shrink"].append(i)
            if price_down and raw24 >= raw80:
                classified["sticky_or_short_build"].append(i)
            if price_up and raw24 >= raw80 and not24 >= not80:
                classified["risk_on_leverage_build"].append(i)

        rv_edges = decile_edges([rv_24[i] for i in eligible if rv_24[i] is not None])
        ret_edges = decile_edges([ret_24[i] for i in eligible if ret_24[i] is not None])
        event_sets = {s: set(v) for s, v in classified.items()}
        results = {}
        for state in states:
            events = classified[state]
            event_keys = {(bin_idx(rv_24[i], rv_edges), bin_idx(ret_24[i], ret_edges), hours[i].hour) for i in events}
            controls = [
                i for i in eligible
                if i not in event_sets[state]
                and (bin_idx(rv_24[i], rv_edges), bin_idx(ret_24[i], ret_edges), hours[i].hour) in event_keys
            ]
            hsum = {}
            for h in horizons:
                hsum[str(h)] = {
                    "event_forward_return": summarize([fwd[h]["return"][i] for i in events]),
                    "control_forward_return": summarize([fwd[h]["return"][i] for i in controls]),
                    "event_forward_abs_return": summarize([fwd[h]["abs_return"][i] for i in events]),
                    "control_forward_abs_return": summarize([fwd[h]["abs_return"][i] for i in controls]),
                    "event_forward_rv": summarize([fwd[h]["rv"][i] for i in events]),
                    "control_forward_rv": summarize([fwd[h]["rv"][i] for i in controls]),
                    "event_mae": summarize([fwd[h]["mae"][i] for i in events]),
                    "control_mae": summarize([fwd[h]["mae"][i] for i in controls]),
                }
            results[state] = {
                "event_count": len(events),
                "control_count": len(controls),
                "first_event": hours[events[0]].isoformat().replace("+00:00", "Z") if events else None,
                "last_event": hours[events[-1]].isoformat().replace("+00:00", "Z") if events else None,
                "horizons": hsum,
            }
        by_symbol[sym] = {
            "hour_count": len(hours),
            "eligible_count": len(eligible),
            "first_hour": hours[0].isoformat().replace("+00:00", "Z") if hours else None,
            "last_hour": hours[-1].isoformat().replace("+00:00", "Z") if hours else None,
            "states": results,
        }

    output = {
        "fixture": str(args.fixture),
        "fixture_versions": sorted(v for v in fixture_versions if v),
        "replay_visibility": sorted(v for v in replay_visibility if v),
        "rolling_hours": args.rolling_hours,
        "states": states,
        "horizons": horizons,
        "by_symbol": by_symbol,
        "decision": "research_only_risk_filter_candidate_first_pass",
        "caveat": "historical observed_at is conservative simulated observed_at, not archived receive time",
    }
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(output, indent=2, sort_keys=True), encoding="utf-8")

    lines = [
        "# Leverage-State Classifier v2 — First-Pass Event Study",
        "",
        "**Decision:** Research Only / Risk Filter Candidate (first pass).",
        "",
        "This study tests whether raw-vs-notional OI state is more useful as a volatility/risk-regime classifier than as standalone directional alpha.",
        "",
        "## Inputs and validation",
        "",
        f"- Fixture: `{args.fixture}`",
        f"- Fixture versions: `{', '.join(output['fixture_versions'])}`",
        f"- Replay visibility: `{', '.join(output['replay_visibility'])}`",
        f"- Rolling threshold window: {args.rolling_hours} hours (~90d)",
        "- Requires Milestone 0 data-quality gate to pass before interpretation.",
        "",
        "## Classifier states",
        "",
        "- `true_deleverage`: price down + notional OI low-tail + raw OI low-tail.",
        "- `passive_notional_shrink`: price down + notional OI low-tail + raw OI flat/up.",
        "- `sticky_or_short_build`: price down + raw OI high-tail.",
        "- `risk_on_leverage_build`: price up + raw OI high-tail + notional OI high-tail.",
        "",
        "## Results summary",
        "",
    ]
    for sym, sdata in by_symbol.items():
        lines += [f"### {sym}", "", f"Eligible hours: {sdata['eligible_count']} / {sdata['hour_count']}", ""]
        for state, r in sdata["states"].items():
            lines.append(f"#### {state}")
            lines.append("")
            lines.append(f"Events: {r['event_count']} | matched-control candidates: {r['control_count']}")
            for h in horizons:
                hs = r["horizons"][str(h)]
                ev_abs = hs["event_forward_abs_return"]["mean"]
                co_abs = hs["control_forward_abs_return"]["mean"]
                ev_ret = hs["event_forward_return"]["mean"]
                co_ret = hs["control_forward_return"]["mean"]
                lines.append(f"- {h}h: mean abs return event={ev_abs}, control={co_abs}; mean return event={ev_ret}, control={co_ret}")
            lines.append("")
    lines += [
        "## Interpretation",
        "",
        "This is a first-pass classifier study. It should not be promoted to Trader handoff from this evidence alone.",
        "The useful question is whether any state reliably annotates fragility/volatility or bad-entry risk after matched controls, not whether it prints a clean directional trade.",
        "",
        "## Validation commands",
        "",
        "```bash",
        "python3 reports/leverage_state_classifier_v2/run_leverage_state_classifier_v2.py \\",
        "  data/regenerated/bybit_leverage_pressure_fixture_365d_20260614_regen.jsonl \\",
        "  --out-json reports/leverage_state_classifier_v2/leverage_state_classifier_v2.json \\",
        "  --out-md reports/leverage_state_classifier_v2/leverage_state_classifier_v2.md",
        "```",
        "",
        "## Caveats",
        "",
        "- Historical `observed_at` is simulated conservatively, not archived live receive time.",
        "- Matched controls are first-pass candidates, not bootstrap confidence intervals.",
        "- Event states can overlap across definitions; this is acceptable for exploratory risk annotation but not final contract semantics.",
        "- No Trader handoff without robustness, stability, and dashboard-level interpretability.",
    ]
    args.out_md.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"out_json": str(args.out_json), "out_md": str(args.out_md), "by_symbol": {k: {"eligible_count": v["eligible_count"], "events": {s: r["event_count"] for s, r in v["states"].items()}} for k, v in by_symbol.items()}}, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
